# Generated by Django 5.2.5 on 2026-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0005_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='week',
            field=models.CharField(default='2026-W11', help_text='Year-week (e.g., 2025-W35)', max_length=10),
        ),
    ]
