# Generated by Django 5.2.5 on 2026-04-22 05:12

import catrentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0006_alter_rental_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='week',
            field=models.CharField(default=catrentapp.models.default_rental_week, help_text='Year-week (e.g., 2025-W35)', max_length=10),
        ),
    ]
