# Generated by Django 5.2.5 on 2026-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0009_operator_created_at_operator_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='site_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
