# Generated by Django 5.2.5 on 2026-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0010_operator_designation_operator_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='checkout_lat',
            field=models.FloatField(blank=True, help_text='Latitude at checkout', null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='checkout_lng',
            field=models.FloatField(blank=True, help_text='Longitude at checkout', null=True),
        ),
    ]
